@echo off
echo Deleting old Docker containers and images...
docker-compose down -v

echo Remove network and images...
docker network prune -f 

echo Starting the Docker containers...
docker-compose up -d --remove-orphans --build
